version: '3'
services:

  discovery:
    image: tanerdiler/service-discovery
    container_name: service-discovery
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  server:
    image: tanerdiler/server
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8090:8090"